<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir).'/app/code/community/Ovs/Magefaker';

return array(
    'Faker\\' => array($vendorDir . '/fzaninotto/faker/src/Faker'),
);
